app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import data_required,length




class Postform(FlaskForm):

    title = StringField("Title Of The Post",validators=[data_required(),length(min=2,max=40)])

    content=TextAreaField("Content",validators=[data_required()])

    submit=SubmitField('Post')

app/main/routes.py
from flask import Blueprint
from flask import request,render_template
from app.models import Post



main=Blueprint('main',__name__)

@main.route("/")
@main.route("/home")
def home():
    page=request.args.get("page",1,type=int)
    post=Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template("home.html",posts=post)




@main.route("/about")
def about():
    return render_template("about.html")

app/post/routes.py
from flask import Blueprint,redirect,render_template,url_for,flash,abort,request
from flask_login import login_required,current_user
from app import db
from app.models import Post
from app.post.forms import Postform




posts=Blueprint('posts',__name__)

@posts.route("/post/new",methods=['POST','GET'])
@login_required
def new_post():
    form = Postform()
    if form.validate_on_submit():
        post = Post(title=form.title.data,content = form.content.data,author = current_user)
        db.session.add(post)
        db.session.commit()
        flash('New Post Has Been Created!!','success')
        return redirect(url_for('main.home'))
    return render_template("new_post.html",form=form,title="Create Post",legend="Create Post")

@posts.route("/post/<int:post_id>")
def post(post_id):
    post=Post.query.get_or_404(post_id)
    return render_template("post.html",title=post.title,post=post)


@posts.route("/post/<int:post_id>/update_post",methods=["POST","GET"])
@login_required
def Update_post(post_id):
    form=Postform()
    post=Post.query.get_or_404(post_id)
    if current_user.id != post.author.id:
        flash("Forbidden!! You don't have the permission to access the requested resource.","danger")
        return redirect(url_for('main.home'))
#        abort(403)

    if form.validate_on_submit():
        post.title=form.title.data
        post.content=form.content.data
        db.session.commit()
        flash(f"Post Edited Successfully!!",'success')
        return redirect(url_for('posts.post',post_id=post_id))
    elif request.method == "GET":
        form.title.data=post.title
        form.content.data=post.content
    return render_template("new_post.html",form=form,title=post.title,legend="Update Post")

@posts.route("/post/<int:post_id>/delete",methods=["POST"])
@login_required
def delete_post(post_id):
    post=Post.query.get_or_404(post_id)
    if current_user.id != post.author.id:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("You're Post has been deleted!",'success')
    return redirect(url_for('main.home'))

app/users/routes.py
from flask import Blueprint,render_template,redirect,flash,url_for,request
from flask_login import login_user,logout_user,current_user,login_required
from app.users.forms import (RegistrationForm,LoginForm,update_form,
                                    RequestResetForm,ResetPasswordForm)
from app.users.utils import save_pic,send_email
from app import db,bcrypt
from app.models import User,Post

users=Blueprint('users',__name__)


@users.route("/register",methods=["POST","GET"])
def register():
    form=RegistrationForm()
    if current_user.is_authenticated:
        flash("Already Logged In","info")
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        hashed_passord=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user1=User(username=form.username.data,email=form.email.data,password=hashed_passord)
        db.session.add(user1)
        db.session.commit()
        flash("Registration Successfull! You can now Log In","success")
        return redirect(url_for('users.login'))
    return render_template("register.html",form=form)
 

@users.route("/login",methods=['POST','GET'])
def login():
    form=LoginForm()
    if current_user.is_authenticated:
        flash("Already Logged In","info")
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=form.remember_me.data)
            flash(f"Logged In as {user.username} Successfully","success")
            next_page=request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash("Login Unsuccessfull! Please Check Your Email and Password","danger")
    return render_template("login.html",form=form)

@users.route("/logout")
def log_out():
    flash(f"{current_user.username} Logged Out Successfully!","success")
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account",methods=["POST","GET"])
@login_required
def my_account():
    form=update_form()
    if form.validate_on_submit():
        if form.pic.data:
            picture=save_pic(form.pic.data)
#            if current_user.image_file != "default.jpg": another way to delete the pic
#                os.remove(f"D:\\VsCode\\Python\\own project\\flask_blog\\static\\profile_pics\\{current_user.image_file}")
            current_user.image_file=picture
        current_user.username=form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash("Account Updated Successfully!!","success")
        return redirect(url_for('users.my_account'))
    elif request.method == "GET":
        form.username.data=current_user.username
        form.email.data=current_user.email
    image_file=current_user.image_file
    return render_template("account.html",image_file=image_file,form=form)


@users.route('/user_posts/<string:username>')
def user_posts(username):
    page=request.args.get('page',1,type=int)
    user=User.query.filter_by(username=username).first_or_404()
    posts=Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template('user_posts.html',title=f'{user.username}-Posts',user=user,posts=posts)


@users.route('/reset_password',methods=['GET','POST'])
def reset_request():
    form=RequestResetForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        send_email(user)
        flash('An email has been sent with the instructions to reset your password!','info')
        return redirect(url_for('users.login'))
    
    return render_template('request_form.html',title='Reset_form',form=form)


@users.route('/reset_password/<token>',methods=['POST','GET'])
def reset_password(token):
    form=ResetPasswordForm()

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    user=User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token','warning')
        return redirect(url_for('users.reset_request'))
    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.new_password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash("The password has been Updated Successfully!You are now able to log in.",'info')
        return redirect(url_for('users.login'))


    return render_template('reset_password.html',title='Reset_password',form=form)

app/templates/about.html
{% extends "layout.html" %}
{% block title%}
About Page
{% endblock title %}
{% block content %}
<h1>About Page</h1>
<p>Page Content</p>
{% endblock %}

app/templates/account.html
{% extends "layout.html" %}
{% block title %}
My Account
{% endblock title %}
{% block content %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username}}</h2>
      <p class="text-secondary">{{ current_user.email }}</p>
    </div>
  </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">My Account</legend>
                <div class="form-group">
                    {{ form.username.label(class='form-control-label')}}
                    {% if form.username.errors %}
                        {{ form.username(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>

                    {% else %}
                        {{ form.username(class='form-control form-control-lg')}}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class='form-control-label')}}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>

                    {% else %}
                        {{ form.email(class='form-control form-control-lg')}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.pic.label()}}
                    {{form.pic(class='form-control-file')}}
                    {% if form.pic.errors %}
                        {% for error in form.pic.errors %}
                        <span class="text-danger">{{error}}</span></br>
                        {% endfor%}
                    {% endif %}

                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}

            </div>
        </form>
</div>
{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}
{% block title %}
Home Page
{% endblock title %}
{% block content %}
{% for post in posts.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{post.author.image_file }}" alt="">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{url_for('users.user_posts',username=post.author.username)}}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    </div>
    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{%  endfor%}
{% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
    <a class="btn btn-info mb-4" href="{{url_for('main.home',page=page_num)}}">{{page_num}}</a>
    {% else %}
      <a class="btn btn-outline-info mb-4" href="{{url_for('main.home',page=page_num)}}">{{page_num}}</a>
    {% endif %}
  {% else %}
  ...
  {% endif %}
{% endfor %}
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">    
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='main.css')}}">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#" onclick="location.reload()">Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{{url_for('main.home')}}">🏠Home<span class="sr-only">(current)</span></a>
        </li>
        {% if current_user.is_authenticated %}
          <li class="nav-item">
              <a class="nav-link" href="{{url_for('posts.new_post')}}" tabindex="-1" aria-disabled="true">➕ New Post</a>
          </li>
          {% endif%}
        </ul>

  <ul class="navbar-nav nav-offset">
            <li class="nav-item dropdown">
            {% if current_user.is_authenticated %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="rounded-circle article-img" src="{{current_user.image_file}}" alt="">
            </a>  
            {% else %}
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
              </a>
            {% endif %}
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              {% if current_user.is_authenticated %}
              <a class="dropdown-item" href="{{url_for('users.my_account')}}">My Account</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{url_for('users.log_out')}}">Log Out</a>
              {% else %}
                <a class="dropdown-item" href="{{url_for('users.login')}}">Log In</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{url_for('users.register')}}">Sign Up</a>  
              {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{url_for('main.about')}}">About❓</a>
            </div>
        </li>
        </ul>
        </div>
    </div>
    </nav>
<main role="main" class="container">
  <div class="row">
    <div class="col-md-7">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category,message in messages %}
          <div class="alert alert-{{ category }}">
            {{ message }}
          </div>
          {% endfor%}
        {% endif %}
      {% endwith %}
      {% block content %}{% endblock %}
    </div>
  <div class="col-md-4 ml-auto">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

app/templates/login.html
{% extends "layout.html" %}
{% block title %}
Log In
{% endblock title %}
{% block content%}
<div class="content-section">
    <form method="POST" action="">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class='form-control-label')}}
                {% if form.email.errors %}
                    {{ form.email(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.email(class='form-control form-control-lg')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.password.label(class='form-control-label')}}
                {% if form.password.errors %}
                    {{ form.password(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.password(class='form-control form-control-lg')}}
                {% endif %}
            </div>
            <div class="form-check">
                {{form.remember_me(class="form-check-input")}}
                {{form.remember_me.label(class="form-check-label")}}

            </div>
        </fieldset>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
        <small class="text-muted ml-2">
            <a href="{{url_for('users.reset_request')}}">Forgot Password?</a>
        </small>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Don't Have An Account? <a class="ml-2" href="{{url_for('users.register')}}">Sign Up</a>
    </small>

</div>
{% endblock content%}

app/templates/new_post.html
{% extends "layout.html" %}
{% block title%}
{{title}}
{% endblock title %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{legend}}</legend>
            <div class="form-group">
                {{ form.title.label(class='form-control-label')}}
                {% if form.title.errors %}
                    {{ form.title(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.title(class='form-control form-control-lg')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.content.label(class='form-control-label')}}
                {% if form.content.errors %}
                    {{ form.content(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class='form-control form-control-lg')}}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>
{% endblock %}

app/templates/post.html
{% extends "layout.html" %}
{% block title %}
{{title}}
{% endblock title %}
{% block content %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{post.author.image_file }}" alt="">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{url_for('users.user_posts',username=post.author.username)}}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    {% if current_user.id == post.author.id %}
      <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.Update_post',post_id=post.id)}}">✏️Update</a>
      <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">🗑️Delete</button>
    {% endif %}
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
 <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLongTitle">Are you sure you want to delete the Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <form action=" {{ url_for('posts.delete_post',post_id=post.id) }} " method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/register.html
{% extends "layout.html" %}
{% block title %}
Sign Up
{% endblock title %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">
                {{ form.username.label(class='form-control-label')}}
                {% if form.username.errors %}
                    {{ form.username(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.username(class='form-control form-control-lg')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.email.label(class='form-control-label')}}
                {% if form.email.errors %}
                    {{ form.email(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.email(class='form-control form-control-lg')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.password.label(class='form-control-label')}}
                {% if form.password.errors %}
                    {{ form.password(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.password(class='form-control form-control-lg')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.confirm_password.label(class='form-control-label')}}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.confirm_password(class='form-control form-control-lg')}}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}

        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{{url_for('users.login')}}">Sign In</a>
    </small>

</div>

{% endblock content %}

app/templates/request_form.html
{% extends "layout.html" %}
{% block title %}
Log In
{% endblock title %}
{% block content%}
<div class="content-section">
    <form method="POST" action="">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class='form-control-label')}}
                {% if form.email.errors %}
                    {{ form.email(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.email(class='form-control form-control-lg')}}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Don't Have An Account? <a class="ml-2" href="{{url_for('users.register')}}">Sign Up</a>
    </small>

</div>
{% endblock content%}

app/templates/reset_password.html
{% extends "layout.html" %}
{% block title %}
{{title}}
{% endblock title %}
{% block content%}
<div class="content-section">
    <form method="POST" action="">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.new_password.label(class='form-control-label')}}
                {% if form.new_password.errors %}
                    {{ form.new_password(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.new_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.new_password(class='form-control form-control-lg')}}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class='form-control-label')}}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class='form-control form-control-lg is-invalid')}}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.confirm_password(class='form-control form-control-lg')}}
                {% endif %}
            </div>


        </fieldset>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>
<div class="border-top pt-3">
</div>
{% endblock content%}

app/templates/user_posts.html
{% extends "layout.html" %}
{% block title %}
{{title}}
{% endblock title %}
{% block content %}
{% for post in posts.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ post.author.image_file }}" alt="">
  <div class="media-body">
    <div class="article-metadata">
  <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    </div>
    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{%  endfor%}
{% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
  <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
    {% else %}
  <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
    {% endif %}
  {% else %}
  ...
  {% endif %}
{% endfor %}
{% endblock %}